spring.application.name=eco

# Server Port
server.port=8080

spring.rabbitmq.addresses=amqps://pktxvbtj:bklvv9eXgBNNVazevnLkjKKaJBeCz-w6@capybara.lmq.cloudamqp.com/pktxvbtj

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Rabbit ke Java
spring.amqp.deserialization.trust.all=true

# Queue & Exchange names
rabbitmq.queue.inventory=order.inventory.queue
rabbitmq.queue.accounting=order.accounting.queue
rabbitmq.exchange=order.fanout.exchange

# Aiven Kafka Broker URL
spring.kafka.bootstrap-servers=your-kafka-instance.aivencloud.com:port

# Keamanan SSL (Sesuaikan path ke file sertifikat yang Anda unduh dari Aiven)
spring.kafka.ssl.truststore-location=file:/path/to/client.truststore.jks
spring.kafka.ssl.truststore-password=password-anda
spring.kafka.ssl.keystore-location=file:/path/to/client.keystore.jks
spring.kafka.ssl.keystore-password=password-anda
spring.kafka.ssl.key-password=password-anda
spring.kafka.security.protocol=SSL

# Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer