spring.application.name=eco

# Server Port
server.port=8080

spring.rabbitmq.addresses=amqps://pktxvbtj:bklvv9eXgBNNVazevnLkjKKaJBeCz-w6@capybara.lmq.cloudamqp.com/pktxvbtj

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Rabbit ke Java
spring.amqp.deserialization.trust.all=true

# Queue & Exchange names
rabbitmq.queue.inventory=order.inventory.queue
rabbitmq.queue.accounting=order.accounting.queue
rabbitmq.exchange=order.fanout.exchange