spring.application.name=eco
server.port=8080

# ==========================================================
# AIVEN KAFKA CONFIGURATION
# ==========================================================

# AIVEN KAFKA CONFIGURATION
spring.kafka.bootstrap-servers=kafka-1477e0bd-narendra-1010.h.aivencloud.com:19328
spring.kafka.security.protocol=SSL

# Gunakan jalur langsung (Legacy format tapi sering lebih ampuh untuk debug)
spring.kafka.properties.ssl.truststore.location=D:/#1 Tugas/EAI/Git-Eco/src/main/resources/certs/client.truststore.jks
spring.kafka.properties.ssl.keystore.location=D:/#1 Tugas/EAI/Git-Eco/src/main/resources/certs/client.keystore.jks
spring.kafka.properties.ssl.truststore.password=password-anda
spring.kafka.properties.ssl.keystore.password=password-anda
spring.kafka.properties.ssl.key.password=password-anda

# Tambahkan ini untuk memastikan identitas server diverifikasi
spring.kafka.properties.ssl.endpoint.identification.algorithm=https

# Tambahkan ini di application.properties
spring.kafka.admin.auto-create=false

# Serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer